# -*- coding: utf-8 -*-
"""Assighnment1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zS2lehkFCq1g3_gevPwHobTjxNV2barA
"""

#   Assignment 1   #


### 1. In the below elements which of them are values or an expression? eg:- values can be integer or string and expressions will be mathematical operators.

*
'hello' 

-87.8
-
/
+
6


# Answer of those question are given below:

1. * = Expression
2. 'hello' = values [string]
3. -87.8 = value [float]
4. - = Expression
5. / = Expression
6. + = Expression
7. 6 = value[int]

#2. What is the difference between string and variable?

The answer of this question is:
The variables are the symbol which we can use to store a data like int,float,complex no etc.
ex:- 'a= 87' or 'a="sameer'
but string is data itself so it cannot store any data.
ex:- b= "ball"
so b is the variable and ball is the string

#3. Describe three different data types.
 data types are given below:

 1.integer
 2.string
 3.complex no
 4. float
 5. list
 6. tuple
 7. dict

#4. What is an expression made up of? What do all expressions do?

Expression is something which create an action between to data.actions like addition , multiplication, division.
simply its a combination of operators.

#5. This assignment statements, like spam = 10. What is the difference between an expression and a statement?
 
 Answer is given below:
  Expression are combination of operator for doing taking an action in between variables or data.
  and Statmentes are the command which user create for compailer or interpreter for exicuting that action.
  
  for ex:-
  a=2+3*5 its an expression which is taking an action
  and
  print(a)
  its an command for exicuting that action:
  'print' is a statment.

#6. After running the following code, what does the variable bacon contain?
   bacon = 22
   bacon + 1

   Answer will be shown below:
   
   23 is the answer.

#7. What should the values of the following two terms be?

'spam'+'spamapam'
 'spam'*3

 Answer will be :
 'spamspamspam' for both terms

#8. Why is eggs a valid variable name while 100 is invalid?

Answer is that:
The variable will be the name or single variable but cant a integer and 100 is a integer so , eggs is a valid name but 100 is not.

#9. What three functions can be used to get the integer, floating-point number, or string version of a value?

for interger it will be :- int()
for string it will be :- str()
for a floating point number it  will be :- float()

#10. Why does this expression cause an error? How can you fix it?

'i have eaten'+99+'burriots'
 
 Well so it will get a TYPE ERROR coz 99 is an integer and remaing both are strings. so if i want to fix this error i will put 99 in beteween "" this.
 like:
 'i have eaten'+'99'+'burriots'
 so output will be:
 i have eaten 99 burriots.